version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: demo
      TZ: Asia/Shanghai
      PGTZ: Asia/Shanghai
    ports:
      - '5432:5432'

  redis:
    image: 'redis:alpine'
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
